apiVersion: okd.alliander.com/v1alpha1
kind: AllianderPipeline
metadata:
  name: frank-test-python
spec:
  sourceConfig:
    gitRepoName: frank-test-python
    sourceSecret: di-github
    jenkinsfilePath: Jenkinsfile.OpenShift    # Optioneel, gaat standaard uit van Jenkinsfile.OpenShift
  enableWebhook: true                         # Optioneel, staat standaard op false. Zet op 'true' als je automatisch een webhook wil aanmaken. Zorg dat het webhook secret bestaat voordat je dit aan zet!
  createWebhook: true                         # Optioneel, OC4, standaard op false. Zet op 'true' als je wil dat er automatisch webhooks naar github worden aangelegd. (En maakt automatisch een nieuw webhook secret aan als dat nog niet bestaat.)
  namePrefix: "auto"                          # Optioneel, gaat standaard uit van "" (lege string)
